### ISSUE TITLE
Can we handle the 'no notification on finalized' issue?

### ISSUE THREAD

**Issue by linuskendall** [rpcpool/yellowstone-grpc#113]
So there is a known issue where Geyser isn't issuing slotNotification for finalized slots: https://github.com/solana-labs/solana/issues/31124

This is probably not critical for this plugin right now, but it would be good for the future.

1. We would need to store all slot notifications in a list ("the list")
2. When we receive a slot update on finalized level from geyser do the following: 
      - Check the parent and parent's parent etc. for the slot update until we find that the parent is missing from the list
      - Issue slot notification for each found parent  ("finalized") and delete them from the list
      - Finally delete the final slot from the list and issue the notification over grpc

**Comment by fanatid** [comment]
v1.14.19 should include a fix for this issue

**Comment by fanatid** [comment]
v1.14.19 includes fix https://github.com/solana-labs/solana/issues/31124
