### ISSUE TITLE
add flag to disable synchronous requests except for ping & subscribe

### ISSUE THREAD

**Issue by mschneider** [rpcpool/yellowstone-grpc#164]
Any use of rwlock open up for client ddos, we would like to prevent our users from using these endpoints: https://github.com/rpcpool/yellowstone-grpc/pull/117

**Comment by fanatid** [comment]
Good point. While locking happens outside of subscribe and write lock takes place in the queue, I think it would be good to make a limit of simultaneous calls and also have a flag that allows disabling these methods at all.
