### ISSUE TITLE
grpc stream close with lagged error with local loop connection

### ISSUE THREAD

**Issue by musitdev** [rpcpool/yellowstone-grpc#180]
I use the current master branch of the plugin and client: 1.9.0+solana.1.16.1 
The validator run Solana 1.16.10
The application is installed on the same server and is connected using localhost.
I experience connection error then disconnection on long-running stream.
Every couple of hours, I got this error: `Status { code: Internal, message: "lagged", source: None }`
After the stream return None, so I close and reconnect.
The stream reopens correctly and restarts until the next lag.

Perhaps the Validator running on the same host take too much CPU and the geyzer stream have some delay and the connection become lagged. The validator works correctly. There's no issue on this side. So, I think, there's still some room to execute other process.  

This lagging occurs very often when working with distant server, which can be normal. Perhaps, it's possible to control the lagging timeout?
The ping stream is activated, and I get a ping every 10 sec.

This is an example of a log when the error occurs:
```
[2m2023-09-01T06:12:49.931199Z[0m [32m INFO[0m [2mstake_aggregate[0m[2m:[0m UpdateOneof::Ping    
[2m2023-09-01T06:12:55.067777Z[0m [33m WARN[0m [2mstake_aggregate[0m[2m:[0m At Confirmed not consecutif slot send: current_slot:219019419 new_slot219019424    
[2m2023-09-01T06:12:56.997345Z[0m [31mERROR[0m [2mstake_aggregate[0m[2m:[0m Geyser stream receive an error has message: 
```
A ping arrive at `06:12:49.931199` then a slot at `06:12:55.067777` and the error at `06:12:56.997345`
The lag arrives nearly 2s after the last logged data. Other slot can have arrived between, but they are not logged. This one is logged because it's not consecutive to the last received confirmed slot.

The program use to test is : https://github.com/blockworks-foundation/solana-rpc-v2/blob/aggregate_stake/stake_aggregate/src/main.rs

**Comment by fanatid** [comment]
You received `lagged` error because the client is not able to consume all messages in time, I think it's because you have a pretty wide filter. Can you try to increase the channel size? If you are the only one who connects to the gRPC it's ok to have a really big value like 1M.
https://github.com/rpcpool/yellowstone-grpc/blob/a3906e0ca241ddf39cf5597057288d94004ae08f/yellowstone-grpc-geyser/config.json#L8

**Comment by musitdev** [comment]
Ok I understand. I'll increase the channel size and do the test.
My client is not very busy when the pb occurs. It uses 10% of the CPU, and the lag occurs when it doesn't process much thing.
Perhaps it's related to the validator activity too?

**Comment by musitdev** [comment]
Ok, as I understand account subscription need more CPU on the validator than block one. Is this that?

**Comment by fanatid** [comment]
I think they require nearly the same % of CPU. `lagged` problem is related with number of messages, what related with subscription filter.

**Comment by fanatid** [comment]
I think they require nearly the same % of CPU. `lagged` problem is related with number of messages, what related with subscription filter.

**Comment by musitdev** [comment]
Yes, I see, they can have much more account update sometime that can create the lag. I've subscribed to stake and vote account.
I'll do a test and tell you.

**Comment by musitdev** [comment]
I've done some test and several epoch change and I didn't have any lag on the connection since I increase the channel capacity. You can close the issue.
