### ISSUE TITLE
stream error with status code Canceled

### ISSUE THREAD

**Issue by imabdulbasit** [rpcpool/yellowstone-grpc#181]
I am getting this error frequently 

`stream error: Status { code: Cancelled, message: "h2 protocol error: error reading a body from connection: stream error received: stream no longer needed", source: Some(hyper::Error(Body, Error { kind: Reset(StreamId(1), CANCEL, Remote) })) }`

client version : v1.7.1+solana.1.16.1

**Comment by fanatid** [comment]
Please check https://github.com/rpcpool/yellowstone-grpc/issues/180

**Comment by imabdulbasit** [comment]
We are using Triton's Grpc endpoint and only have 2 program ids in accounts filter
