### ISSUE TITLE
Add optional ping field to SubscribeRequest

### ISSUE THREAD

**Issue by fanatid** [rpcpool/yellowstone-grpc#225]
From [Helius](https://www.helius.dev/) report: [Cloudflare](https://www.cloudflare.com/) terminate duplex stream (`subscribe` method) if the client does not send any message during 30s. Client can re-send the filter every N seconds but `ping` field would be better.

cc @vovkman

**Comment by vovkman** [comment]
Small adjustment - the stream takes 10 mins to terminate in Cloudflare if no client message sent in duplex
