### ISSUE TITLE
Latest compatible validator

### ISSUE THREAD

**Issue by mohsen-vybenetwork** [rpcpool/yellowstone-grpc#243]
Hey Guys
Following your advice, we've decided to migrate our production to Dragon Mouth instead of Geyser Owner Avatar [Solana AccountsDB Plugin Kafka].

Given that the current floor version of Solana is 1.16.17 and, according to the README, the original validator is not compatible with the plugin, we need to know the latest release or branch of the Solana validator that we should use to build from source. The documentation indicates that the branch is based on 1.16.16, which does not meet the requirements of the Solana Mainnet validator.

Any guidance on the appropriate Solana validator release or branch would be greatly appreciated.

**Comment by fanatid** [comment]
Hi @mohsen-vybenetwork!

Basically for compatibility, you need to cherry-pick this commit on top of the branch that you want to use https://github.com/rpcpool/solana-public/commit/922d06aab6b6d4e866ddb1cef31362b249bf2576.
Here is a tag for `v1.16.17`: https://github.com/rpcpool/solana-public/commits/v1.16.17-geyser-block-v3

![image](https://github.com/rpcpool/yellowstone-grpc/assets/2633065/fa968575-6fdb-4aa5-9bf4-da1346961f46)
