### ISSUE TITLE
Broker: Message size too large

### ISSUE THREAD

**Issue by mohsen-vybenetwork** [rpcpool/yellowstone-grpc#259]
Hey @fanatid
It seems that sometimes the message size is too large. How is this possible when we subscribe only to block_meta or slot?
This is the message we receive, and immediately after getting this error, the grpc2kafka app fails.
`MessageSizeTooLarge (Broker: Message size too large) `

**Comment by fanatid** [comment]
Did you try to increase `message.max.bytes`?

**Comment by fanatid** [comment]
server/topic also should be configured?

**Comment by mohsen-vybenetwork** [comment]
Yes We have set that to Max message supported size. Wondering the message can be greater than 8MB ?
` maximum allowed value of of 8388608`
Surprisingly, there are some cases where we receive a large message that is not acceptable to the broker.

**Comment by fanatid** [comment]
Yes, blocks with transactions and accounts is definitely can be bigger than 8MB. IIRC last block in the epoch generates files about 60MB in BigTable, so I'd expect ~100MB in gRPC for such blocks.
In Rust client, we set 64MiB by default https://github.com/rpcpool/yellowstone-grpc/blob/96477484b7be44e69656c3e76ab64d0100e926c3/yellowstone-grpc-client/src/lib.rs#L113

**Comment by mohsen-vybenetwork** [comment]
Oops. Sounds interesting. As far as I know, Kafka cannot handle such a large message; the maximum message size is around 8MB. What about only block_meta? I think it can be relatively smaller, possibly less than 8MB, because we get this error even for block_meta only.

**Comment by fanatid** [comment]
I do not know much about kafka, are you sure about 8MB limit? if so it would be very sad :confused: 
BlockMeta should be pretty small -- https://github.com/rpcpool/yellowstone-grpc/blob/159b12b29e40cc698ccfda7a349fba479125cdd8/yellowstone-grpc-proto/proto/geyser.proto#L159-L168
I'd only worried about `rewards` but more than 1MB? :open_mouth: 
Would you be able to modify `grpc2kafka` and log the message (size and details?) on error? Would be interesting to see what causes a problem. Let me know if you need help with the patch.

**Comment by mohsen-vybenetwork** [comment]
Thank you for being so amazing. You've been always receptive about our requests. 
Which file I have to change to patch? Would be perfect if you help me on that.

**Comment by fanatid** [comment]
hey @mohsen-vybenetwork, any results?

**Comment by mohsen-vybenetwork** [comment]
@fanatid 
Had an issue with our rpc server. Fixed 3 hours ago and re-ran the new branch. Will update you once we get the error.

**Comment by mohsen-vybenetwork** [comment]
@fanatid 
```
`topic: "dragon-slot", timestamp: NotAvailable, partition: 0, offset: -1, headers: None }))), message size: 46137196, msg kind BlockMeta
Error: Message production error: MessageSizeTooLarge (Broker: Message size too large)

Caused by:
    MessageSizeTooLarge (Broker: Message size too large`
```

**Comment by linuskendall** [comment]
In your Kafka broker config have you updated "max.message.bytes"? This is
typically something you need to change on the Kafka server configuration
side rather than in the grpc2kafka config.

A sample broker if you are using the Confluent/Kafka start up scripts would
be:

```
kafka-configs.sh --bootstrap-server localhost:9092 \
                --alter --entity-type topics \
                --entity-name configured-topic \
                --add-config max.message.bytes=31457640
```

This would set it as 30mib.

**Comment by mohsen-vybenetwork** [comment]
@linuskendall 
Yep. And It's just for block_meta why it should be 46MB ???

**Comment by fanatid** [comment]
> This would set it as 30mib.

from @mohsen-vybenetwork logs looks like we need 46mb+ :grinning:  probably set 64mib would be a good target because we have that value in rust client and nobody complains about the big message

**Comment by fanatid** [comment]
> And It's just for block_meta why it should be 46MB ???

sad that we not add slot number to warn message, probably it was slot https://explorer.solana.com/block/235440004/rewards with a lot of rewards

**Comment by mohsen-vybenetwork** [comment]
@fanatid It's so weird to me if the message is that large why we don't have any issue with solana-accountsdb-plugin-kafka plugin ?
Same topic configuration. Also why block_meta is 46MB ? I think the slot size could be 46MB but we only need block_meta out of that 46MB which should be so small.

**Comment by fanatid** [comment]
`solana-accountsdb-plugin-kafka` doesn't subscribe to block updates
`Block` message also can be huge and will throw an error but because `BlockMeta` received before we see error only for `BlockMeta`

**Comment by mohsen-vybenetwork** [comment]
Hmm. Trying to understand. A Block/Slot could be even 100MB but BlockMeta which only contains metadata should be relatively small. Based on my assumption, we get a huge message then extract BlockMeta which is small and then send the small data(BlockMeta) to a topic.  Am I wrong ?

**Comment by fanatid** [comment]
BlockMeta: we get this struct as input https://docs.rs/solana-geyser-plugin-interface/latest/solana_geyser_plugin_interface/geyser_plugin_interface/struct.ReplicaBlockInfoV3.html usually small, only number of rewards may affect the size

Slot: always small, has only slot number, parent slot number, commitment level

Block: same as BlockMeta but optionally can include all accounts / transactions / entries (can be huge because includes accounts data)

**Comment by mohsen-vybenetwork** [comment]
Thank you for the information. We have another configuration for slots only, and I just checked, it failed due to message size. I believe the issue with kafka2rpc persists regardless of the subscription size. It seems to check the block size instead of the actual subscription, as the slot is always small, but it failed similar to BlockMeta.

**Comment by fanatid** [comment]
`"slots": {"client": { "filter_by_commitment": null }},`

Is this configuration in `request` object with `block`/`blockmeta`? or a separate config for grpc2kafka?

**Comment by mohsen-vybenetwork** [comment]
Nope totally separate config.

**Comment by fanatid** [comment]
Interesting, can you please: paste `request` config and run the patched grpc2kafka version so we would able to see the message kind before error? Thanks for debugging :)

**Comment by mohsen-vybenetwork** [comment]
@fanatid Thank you for your great help. We resolved the issue by migrating to a hosted Kafka and increasing the message size to over 200MB.
