### ISSUE TITLE
Failed to load the Geyser plugin

### ISSUE THREAD

**Issue by dziunincode69** [rpcpool/yellowstone-grpc#298]
``Hello. 
why I get the following error
<img width="1224" alt="image" src="https://github.com/rpcpool/yellowstone-grpc/assets/55616294/a8aa33a2-834f-4ab8-baf9-9d448a68aa0b">

here is my startup script 
`#!/bin/bash
solana-validator \
--identity /node/node_identity.json \
--full-rpc-api \
--no-voting \
--ledger /node/solana-ledger \
--accounts /node/solana-accounts \
--snapshots /node/solana-snapshot \
--limit-ledger-size 100000000 \
--log - \
--rpc-port 8899 \
--rpc-bind-address 127.0.0.1 \
--private-rpc \
--dynamic-port-range 8000-8500 \
--no-port-check \
--enable-cpi-and-log-storage \
--rpc-threads 512 \
--tpu-use-quic \
--geyser-plugin-config=/root/geyser/config.json`

and here is my config file
`root@XXX:/node# cat /root/geyser/config.json`

`{
    "libpath": "/root/geyser/build-yellowstone/libyellowstone_grpc_geyser.so",
    "log": {
        "level": "info"
    },
    "grpc": {
        "address": "0.0.0.0:10000",
        "tls_config": {
            "cert_path": "",
            "key_path": ""
        },
        "max_decoding_message_size": "4_194_304",
        "snapshot_plugin_channel_capacity": null,
        "snapshot_client_channel_capacity": "50_000_000",
        "channel_capacity": "100_000",
        "unary_concurrency_limit": 100,
        "unary_disabled": false,
        "filters": {
            "accounts": {
                "max": 1,
                "any": false,
                "account_max": 10,
                "account_reject": ["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"],
                "owner_max": 10,
                "owner_reject": ["11111111111111111111111111111111"]
            },
            "slots": {
                "max": 1
            },
            "transactions": {
                "max": 1,
                "any": false,
                "account_include_max": 10,
                "account_include_reject": ["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"],
                "account_exclude_max": 10,
                "account_required_max": 10
            },
            "blocks": {
                "max": 1,
                "account_include_max": 10,
                "account_include_any": false,
                "account_include_reject": ["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"],
                "include_transactions": true,
                "include_accounts" : false,
                "include_entries" : false
            },
            "blocks_meta": {
                "max": 1
            },
            "entry": {
                "max": 1
            }
        }
    },
    "prometheus": {
        "address": "0.0.0.0:8999"
    },
    "block_fail_action": "log"
}`

I've spent a lot of time on this error, I've made sure the directory and path are correct.

`root@XXX:/node# ls -l /root/geyser/build-yellowstone/libyellowstone_grpc_geyser.so
-rwxrwxrwx 2 root root 330555736 Mar 14 22:16 /root/geyser/build-yellowstone/libyellowstone_grpc_geyser.so`

**Comment by fanatid** [comment]
- did you compile the plugin yourself for your OS / libs?
- do you run a validator from the root too? does that user have access to `/root/geyser/build-yellowstone/libyellowstone_grpc_geyser.so`?
- on screenshot, location is `/root/build-yellowstone/libyellowstone_grpc_geyser.so`, not `/root/geyser/build-yellowstone/libyellowstone_grpc_geyser.so`

**Comment by dziunincode69** [comment]
1. Yes i compile the plugin on my machine using cargo build
2. yes i run validator from root 
3. sorry wrong screenshot, here is the correct screenshot
<img width="1238" alt="image" src="https://github.com/rpcpool/yellowstone-grpc/assets/55616294/90d23993-a3b3-4411-a24f-c937bf265487">

**Comment by dziunincode69** [comment]
fixed by deleting
`        "tls_config": {
            "cert_path": "",
            "key_path": ""
        },`

**Comment by xxfs** [comment]
> fixed by deleting ` "tls_config": { "cert_path": "", "key_path": "" },`

it works.
