### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by karneges** [rpcpool/yellowstone-grpc#299]
I worked with 1.7.15 version. It were 
- https://github.com/rpcpool/solana-public/tree/v1.17.15-block-cache
- https://github.com/rpcpool/yellowstone-grpc/tree/v1.12.0%2Bsolana.1.17.15
It worked fine

Now I am trying to use 1.7.24
- https://github.com/rpcpool/solana-public/tree/v1.17.24-block-cache
- https://github.com/rpcpool/yellowstone-grpc/tree/v1.13.0%2Bsolana.1.17.24

And each time I receive a segmentation fault error. Here is my solana-validator config. The same behavior with 1.8.4

solana-validator \
    --geyser-plugin-config /root/yellowstone-grpc/yellowstone-grpc-geyser/config.json \
    --identity validator-keypair.json \
    --vote-account vote-account-keypair.json \
    --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
    --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
    --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
    --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
    --only-known-rpc \
    --log /home/sol/solana-validator.log \
    --ledger /mnt/ledger \
    --rpc-port 8899 \
    --no-voting \
    --dynamic-port-range 8000-8020 \
    --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
    --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
    --wal-recovery-mode skip_any_corrupted_record \
    --limit-ledger-size

**Comment by jin10086** [comment]
hello , i have the same question ,  How do you solve it?
