### ISSUE TITLE
Fail to load geyser

### ISSUE THREAD

**Issue by xll970211** [rpcpool/yellowstone-grpc#303]
when I use command solana-validator plugin load config. It display `JsonRpcError(Error { code: InvalidRequest, message: "No geyser plugin service", data: None })`
solana 1.18.4

**Comment by fanatid** [comment]
Can you say exactly what you are doing (in steps)? `"No geyser plugin service"` error is only possible in the admin interface when plugins were not loaded on startup.

Error is not related to gRPC plugin.
