### ISSUE TITLE
add geyser plugin problem

### ISSUE THREAD

**Issue by xll970211** [rpcpool/yellowstone-grpc#304]
add geyser plugin successful,but my solana node can't sync. It display
![image](https://github.com/rpcpool/yellowstone-grpc/assets/43258690/66d157e6-df74-4446-a09b-d3f0f05cc5d0)
no error
solana 1.18.4
yellowstone-grpc-geyser v1.13.0+solana.1.18.4

**Comment by fanatid** [comment]
Why do you think that this was caused by gRPC plugin?

**Comment by xll970211** [comment]
when I remove plugin is ok

**Comment by p0st1t** [comment]
Same here. @xll970211 , have you found a solution please?

**Comment by luketree1** [comment]
> when I remove plugin is ok

how did you solve it?
