### ISSUE TITLE
 how to install on Ubuntu 22.04

### ISSUE THREAD

**Issue by paulalsop** [rpcpool/yellowstone-grpc#317]
I have a question. I have installed a Solana validator node on Ubuntu 22.04, and I want to install yellowstone-grpc on this node. Can you tell me how to install it? Can you provide me with detailed steps? I've been looking for a long time and don't know how to install it.

**Comment by Lusitaniae** [comment]
download geyser plugin in releases, in this case the 22 attached to the name means its built for Ubuntu 22
https://github.com/rpcpool/yellowstone-grpc/releases/download/v1.13.0%2Bsolana.1.18.9/yellowstone-grpc-geyser-release22-x86_64-unknown-linux-gnu.tar.bz2

 
Start solana with flag ` --geyser-plugin-config`
`solana-validator --geyser-plugin-config yellowstone-grpc-geyser/config.json`

Use example config file:
https://github.com/rpcpool/yellowstone-grpc/blob/master/yellowstone-grpc-geyser/config.json

**Comment by paulalsop** [comment]
I understand, it's a configuration for solana-validator. If my Solana node is running, it means I need to stop it first, and then start it with the command "solana-validator --geyser-plugin-config yellowstone-grpc-geyser/config.json", right? Do I need to specify "--identity" again?

**Comment by paulalsop** [comment]
solana-validator --identity  /home/solv/mainnet-validator-keypair.json --geyser-plugin-config yellowstone-grpc-geyser/config.json

**Comment by paulalsop** [comment]
After the restart, is the address still the original RPC port? My original port is: 127.0.0.1:8899.

**Comment by Lusitaniae** [comment]
yes, requires a restart if you changing params/flags 

yes, keep all the flags/arguments you have right now and add the one for geyser

if you keep all params RPC still available under same PORT :8899

**Comment by paulalsop** [comment]
I added "--geyser-plugin-config yellowstone-grpc-geyser/config.json" to the original "/home/solv/start-validator.sh" file. Then start like this:

```bash
#!/bin/bash
exec solana-validator \
--identity /home/solv/mainnet-validator-keypair.json \
--vote-account /home/solv/mainnet-vote-account-keypair.json \
--log /home/solv/solana-validator.log \
--accounts /mnt/accounts \
--ledger /mnt/ledger \
--entrypoint entrypoint.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
--known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
--known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
--known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
--known-validator C1ocKDYMCm2ooWptMMnpd5VEB2Nx4UMJgRuYofysyzcA \
--known-validator GwHH8ciFhR8vejWCqmg8FWZUCNtubPY2esALvy5tBvji \
--known-validator 6WgdYhhGE53WrZ7ywJA15hBVkw7CRbQ8yDBBTwmBtAHN \
--known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
--dynamic-port-range 8000-8020 \
--rpc-bind-address 0.0.0.0 \
--rpc-port 8899 \
--wal-recovery-mode skip_any_corrupted_record \
--limit-ledger-size \
--geyser-plugin-config yellowstone-grpc-geyser/config.json \
```

**Comment by paulalsop** [comment]
jupiter-swap-api, here --rpc-url and --yellowstone-grpc-endpoint whether to write 127.0.0.1:8899, and what is yellowstone-grpc-x-token? How to write this command? RUST_LOG=info ./jupiter-swap-api --rpc-url <RPC-URL> --yellowstone-grpc-endpoint <GRPC-ENDPOINT> --yellowstone-grpc-x-token <X-TOKEN>

**Comment by Lusitaniae** [comment]
token is not required if you connect directly to the RPC (no proxies or any sort of auth)

**Comment by paulalsop** [comment]
yellowstone-grpc-geyser/config.json
I am running this default config.json configuration on a Solana mainnet validator node. The validator node keeps restarting while syncing data. Does this default configuration need to be modified?

**Comment by fanatid** [comment]
@paulalsop remove `tls_config` field in the default config, if you check the validator logs you will see an error about the geyser
