### ISSUE TITLE
memory allocation error failed to load geyser plugin

### ISSUE THREAD

**Issue by mrjamesdoan** [rpcpool/yellowstone-grpc#324]
Hello, I'm trying to load the compiled geyser plugin, but also get an error when starting the validator

[2024-04-16T22:06:23.194831087Z INFO  solana_geyser_plugin_manager::geyser_plugin_service] Starting GeyserPluginService from config files: ["yellowstone-grpc/yellowstone-grpc-geyser/config.json"]
memory allocation of 140047115561648 bytes failed

Can anybody help ?

**Comment by Juanito87** [comment]
First you'll need to paste you config file. That werror is usually an error in the config.

**Comment by McSim85** [comment]
If some find this issue.
The same happened to me when I ran 1.17.34 solana with 1.18.15 geyser lib.

**Comment by Lusitaniae** [comment]
Correct, most likely explanation is solana version doesn't match the geyser build

We usually do exact match on solana versions with geyser versions
