### ISSUE TITLE
JsonParsed

### ISSUE THREAD

**Issue by Giopi** [rpcpool/yellowstone-grpc#325]
When i subscribe to new transaction can i have transaction in jsonParsed for spl-token?
Thanks

**Comment by fanatid** [comment]
No, you can not..
if you use Rust you can use some functions from `mod convert_from` https://github.com/rpcpool/yellowstone-grpc/blob/9bf0fb71d46a8fb6a783b2fdaf8ef0fea592e54f/yellowstone-grpc-proto/src/lib.rs#L266
if you use JS you would need to decode all data yourself

**Comment by donghanji** [comment]
Is it possible to implement support for `jsonParsed` using the parsing procedure in the official source code of solana, which is mainly parsed in  [/transaction-status/](https://github.com/solana-labs/solana/tree/master/transaction-status/src)
