### ISSUE TITLE
Update yellowstone-grpc-proto version on the latest Release

### ISSUE THREAD

**Issue by 0xJchen** [rpcpool/yellowstone-grpc#337]
The latest release has `solana-account-decoder = "=1.18.12"` with `yellowstone-grpc-proto = 1.14.0`

While on the default crate`yellowstone-grpc-proto` at `https://crates.io/crates/yellowstone-grpc-proto/1.14.0/dependencies` has dependency `>=1.17.28, <1.18.0 for solana-account-decoder`

**Comment by fanatid** [comment]
1.18 introduced a new entry structure so you can not use the published package on crates with both 1.17 and 1.18
if you want to use 1.18 you need to use it from github
