### ISSUE TITLE
compability of output grpc and websockets

### ISSUE THREAD

**Issue by benjiqq** [rpcpool/yellowstone-grpc#346]
translating between rpc/websocket and rpc shows differences. grpc lacking 

* inner instructions 
* signature is base64, need to convert back to base58

```
"innerInstructions": [
            {
                "index": 3,
                "instructions": [
                    {
                        "program": "spl-token",
                        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
                        "parsed": {
                            "info": {
                                "amount": "2922218000000",
                                "authority": "5zy5xLLzwXzMyqqnnHDrwpwrtJ5JAVCQkqRf8wqK1GM4",
                                "destination": "4xBorF4Tn6RtFPZ4nzBzeQY4rZjE2a524jsiDHHEUhDs",
                                "source": "CqBuJvTohrCSVMd519nGEvFoJcyTLfm7pCjqfkXQG91z"
                            },
                            "type": "transfer"
                        },
                        "stackHeight": 2
                    },
                    {
                        "programId": "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P",
                        "accounts": [
                            "Ce6TQqeHC9p8KetsN6JsjHK7UTZk7nasjjnr7XxXp9F1"
                        ],
                        "data": "3Qf1fH3KwcWxhgT6SC3VMtJ8b21XppZLhjkZnvHnaSSwtQ8BPrJQQjgxK915CqniG8pR8xcWuSjtH2yeKJVKe4bH9QBsHgGDYGyxhBVgL18xWx5eXzdNdcKX1WaMATrfQxrouoiCp9WCqHPp21WqApW9w7WjX4byzCXMd9",
                        "stackHeight": 2
                    }
                ]
            }
        ],
```
grpc

```
"innerInstructions": [
          {
            "index": 3,
            "instructions": [
              {
                "programIdIndex": 12,
                "accounts": "BQQA",
                "data": "A4AOxGGoAgAA",
                "stackHeight": 2
              },
              {
                "programIdIndex": 8,
                "accounts": "DQ==",
                "data": "5EWlLlHLmh2923/TTuZh7ujTzGywSpTLwx5ax8ampH8cBMiMWIw8/K7H13VmkPx46dzHCwAAAACADsRhqAIAAABKSEURywcjENtMGAq78wKVaWDLSPXmsYsICebaSxhbx5DVUGYAAAAAPFBN1woAAAB/In7SxHQCAA==",
                "stackHeight": 2
              }
            ]
          }
        ],
```

python code for this subscribe request

```
transactions_filter = SubscribeRequestFilterTransactions(
        vote=False,
        failed=False,
        signature=None,
        account_include=["675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"],
        account_exclude=[],
        account_required=[]
    )

    # Create the subscribe request
    request = SubscribeRequest(
        slots=[],
        accounts={},
        transactions={"client": transactions_filter},
        transactions_status={},
        entry={},
        blocks={},
        blocks_meta={},
        commitment=None,
        accounts_data_slice=[],
        ping=None
    )
```

**Comment by fanatid** [comment]
You should  be able to get the same output as rpc / websocket if decode gRPC output to `TransactionWithStatusMeta` and call `.encode`
https://docs.rs/solana-transaction-status/latest/solana_transaction_status/enum.TransactionWithStatusMeta.html#method.encode

**Comment by PUXLBIY** [comment]
@benjiqq Have you encountered this problem? gRPC outputs data in an incomprehensible form
`signature: "\255\224RQ\307\241+\301\252d\260\361\272\235\027\6\217H\325\237\310\371y\206\346\303\275\220C\253@\374\262\002\016-\277I\313\266D3"\342\235\305\316\022\214-i\271\362I\335\211<\360\026^\233&\014"
transaction {
  signatures: "\255\224RQ\307\241+\301\252d\260\361\272\235\027\6\217H\325\237\310\371y\206\346\303\275\220C\253@\374\262\002\016-\277I\313\266D3"\342\235\305\316\022\214-i\271\362I\335\211<\360\026^\233&\014"
  signatures: "@ai8\032f\2213\277\034\217\223\276\t\313\342\251\243\206lD\253\241~j\276Q\363\025xd\316\360\237\251\262\241\217\250\317=\212\236\232y\316\255~\372\234p<\340\023\303\312\307\366\266\327\267\311\200\t"
  message {
    header {
      num_required_signatures: 2
      num_readonly_unsigned_accounts: 10
    }
    account_keys: "\240\266\257\003\351F\375 \254F\246\334\362\205\307\231"\010d;\037\325\277N\033{\3544\001l\346\024"
    account_keys: "\321\247\244\210\247\036\rs\004*\310e\303xf\017\027\335\371W5\032\233\326\221\365\2113\355\177\267Y"
    account_keys: "\3658o\022\275\227U\237\206\344n\272\023x{(\370\323\302Bh\346\271\361\003f~\037\240U(\233"
    account_keys: "\232\302\0016\243\207\t\215\370\201\337\267\372\214\037EE\325V\223\261Y\353\224\026\241\241\372\220\320\242\344"
    account_keys: "\257\203xX;]\H?\314\232\312(_\001\013\237l\315\016j#\201,]\311\021+\372<fG"
    account_keys: "\375q\016{\320,\264\\241S\276\357\335\350\231\256\035\266\272u\010v\330S\000\326]\013\363\\257f"
    account_keys: "0\363\265\202\320\366\346"}\037d-+5D4\376\367\234\037\242@\032T\203\273{\276=\254\342\340"
    account_keys: "\255\021\346\244\374)D\244\372\202Q\276\370\025Bn\033\373(\306\266dfw`|j\331\365f\246F"
    account_keys: "\003\006Fo\345!\0272\377\354\255\272r\303\233\347\274\214\345\273\305\367\022k,C\233:@\000\000\000"
    account_keys: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
    account_keys: "\001V\340\366\223fZ\317D\333\025h\277\027[\252Q\211\313\227\365\322\377;e]+\266\375m\030\260"
    account_keys: "\006\305\301\316c\215%g\322dh\260^\271Q\321\242\215\314n\0224\202\265\306u\024\227p\346+\362"
    account_keys: ":\206^i\356\017T\200\312\274\366cW\344\334/\030\325\215E\301\352t\211\3737#\331y<r\246"
    account_keys: "\013pe\261\343\321|E8\235R\177k\004\303\315X\270ls\032\240\375\265I\266\321\274\003\370)F"
    account_keys: "\006\335\366\341\327e\241\223\331\313\341F\316\353y\254\034\264\205\355_[7\221:\214\365\205~\377\000\251"
    account_keys: "\214\227%\217N$\211\361\273=\020)\024\216\r\203\013Z\023\231\332\377\020\204\004\216{\330\333\351\370Y"
    account_keys: "\006\247\325\027\031,\Q!\214\311L=J\361\177X\332\356\010\233\241\375D\343\333\331\212\000\000\000\000"
    account_keys: "\254\3616\353\001\374\034N\210=#\310\265\204J\265\2327\366j\335W\305\351\254;S\340Y\323\d"
    recent_blockhash: "s\250\250\317\222\007\033=z\304\222^Q\272\r6\r\224\322\201"\005\225\030f\000\020\316R\212\024\326"
    instructions {
      program_id_index: 8
      data: "\002\003\245\002\000"
    }
    instructions {
      program_id_index: 8
      data: "\003\nL\270\000\000\000\000\000"
    }
    instructions {
      program_id_index: 9
      accounts: "\000\002"
      data: "\002\000\000\000\000\t=\000\000\000\000\000"
    }
    instructions {
      program_id_index: 10
      accounts: "\001\013\003\004\014\r\005\000\t\016\017\020\021\n"
      data: "\030\036\310(\005\034\007w\023\000\000\000Official Story A.I \007\000\000\000StoryAIC\000\000\000https://ipfs.io/ipfs/QmQj4FTnYsUc5nmU5gdJkDwodVvBeQQMV5NMng9a9apSes"
    }
    instructions {
      program_id_index: 15
      accounts: "\000\006\000\001\t\016"
      data: "\001"
    }
    instructions {
      program_id_index: 10
      accounts: "\014\007\001\003\004\006\000\t\016\020\021\n"
      data: "f\006=\022\001\332\353\352\377\200}4\376<\000\000\000\301fx\000\000\000\000"
    }
    versioned: true
  }
}
meta {
  fee: 2103315
  pre_balances: 10875517572
  pre_balances: 0
  pre_balances: 207594496815
  pre_balances: 0
  pre_balances: 0
  pre_balances: 0
  pre_balances: 0
  pre_balances: 320190076509178
  pre_balances: 1
  pre_balances: 1
  pre_balances: 1141440
  pre_balances: 338333919
  pre_balances: 140530000
  pre_balances: 1141440
  pre_balances: 934087680
  pre_balances: 731913600
  pre_balances: 1009200
  pre_balances: 112000010
  post_balances: 8827526577
  post_balances: 1461600
  post_balances: 207598496815
  post_balances: 2001231920
  post_balances: 2039280
  post_balances: 15115600
  post_balances: 2039280
  post_balances: 320190096509178
  post_balances: 1
  post_balances: 1
  post_balances: 1141440
  post_balances: 338333919
  post_balances: 140530000
  post_balances: 1141440
  post_balances: 934087680
  post_balances: 731913600
  post_balances: 1009200
  post_balances: 112000010
  inner_instructions {
    index: 3
    instructions {
      program_id_index: 9
      accounts: "\000\001"
      data: "\000\000\000\000`M\026\000\000\000\000\000R\000\000\000\000\000\000\000\006\335\366\341\327e\241\223\331\313\341F\316\353y\254\034\264\205\355_[7\221:\214\365\205~\377\000\251"
      stack_height: 2
    }
    instructions {
      program_id_index: 14
      accounts: "\001"
      data: "\024\006\006\305\301\316c\215%g\322dh\260^\271Q\321\242\215\314n\0224\202\265\306u\024\227p\346+\362\000"
      stack_height: 2
    }
    instructions {
      program_id_index: 9
      accounts: "\000\003"
      data: "\000\000\000\0000\314\022\000\000\000\000\0001\000\000\000\000\000\000\000\001V\340\366\223fZ\317D\333\025h\277\027[\252Q\211\313\227\365\322\377;e]+\266\375m\030\260"
      stack_height: 2
    }
    instructions {
      program_id_index: 15
      accounts: "\000\004\003\001\t\016"
      data: "\000"
      stack_height: 2
    }
    instructions {
      program_id_index: 14
      accounts: "\001"
      data: "\025\007\000"
      stack_height: 3
    }
    instructions {
      program_id_index: 9
      accounts: "\000\004"
      data: "\000\000\000\000\360\035\037\000\000\000\000\000\245\000\000\000\000\000\000\000\006\335\366\341\327e\241\223\331\313\341F\316\353y\254\034\264\205\355_[7\221:\214\365\205~\377\000\251"
      stack_height: 3
    }
    instructions {
      program_id_index: 14
      accounts: "\004"
      data: "\026"
      stack_height: 3
    }
    instructions {
      program_id_index: 14
      accounts: "\004\001"
      data: "\022\232\302\0016\243\207\t\215\370\201\337\267\372\214\037EE\325V\223\261Y\353\224\026\241\241\372\220\320\242\344"
      stack_height: 3
    }
    instructions {
      program_id_index: 13
      accounts: "\005\001\013\000\013\t"
      data: "!\023\000\000\000Official Story A.I \007\000\000\000StoryAIC\000\000\000https://ipfs.io/ipfs/QmQj4FTnYsUc5nmU5gdJkDwodVvBeQQMV5NMng9a9apSes\000\000\000\000\000\000\000"
      stack_height: 2
    }
    instructions {
      program_id_index: 9
      accounts: "\000\005"
      data: "\002\000\000\000P\245\346\000\000\000\000\000"
      stack_height: 3
    }
    instructions {
      program_id_index: 9
      accounts: "\005"
      data: "\010\000\000\000_\002\000\000\000\000\000\000"
      stack_height: 3
    }
    instructions {
      program_id_index: 9
      accounts: "\005"
      data: "\001\000\000\000\013pe\261\343\321|E8\235R\177k\004\303\315X\270ls\032\240\375\265I\266\321\274\003\370)F"
      stack_height: 3
    }
    instructions {
      program_id_index: 14
      accounts: "\001\004\013"
      data: "\007\000\200\306\244~\215\003\000"
      stack_height: 2
    }
    instructions {
      program_id_index: 14
      accounts: "\001\013"
      data: "\006\000\000"
      stack_height: 2
    }
    instructions {
      program_id_index: 10
      accounts: "\021"
      data: "\344E\245.Q\313\232\035\033r\251M\336\353cv\023\000\000\000Official Story A.I \007\000\000\000StoryAIC\000\000\000https://ipfs.io/ipfs/QmQj4FTnYsUc5nmU5gdJkDwodVvBeQQMV5NMng9a9apSes\321\247\244\210\247\036\rs\004*\310e\303xf\017\027\335\371W5\032\233\326\221\365\2113\355\177\267Y\232\302\0016\243\207\t\215\370\201\337\267\372\214\037EE\325V\223\261Y\353\224\026\241\241\372\220\320\242\344\240\266\257\003\351F\375 \254F\246\334\362\205\307\231"\010d;\037\325\277N\033{\3544\001l\346\024"
      stack_height: 2
    }
  }
  inner_instructions {
    index: 4
    instructions {
      program_id_index: 14
      accounts: "\001"
      data: "\025\007\000"
      stack_height: 2
    }
    instructions {
      program_id_index: 9
      accounts: "\000\006"
      data: "\000\000\000\000\360\035\037\000\000\000\000\000\245\000\000\000\000\000\000\000\006\335\366\341\327e\241\223\331\313\341F\316\353y\254\034\264\205\355_[7\221:\214\365\205~\377\000\251"
      stack_height: 2
    }
    instructions {
      program_id_index: 14
      accounts: "\006"
      data: "\026"
      stack_height: 2
    }
    instructions {
      program_id_index: 14
      accounts: "\006\001"
      data: "\022\240\266\257\003\351F\375 \254F\246\334\362\205\307\231"\010d;\037\325\277N\033{\3544\001l\346\024"
      stack_height: 2
    }
  }
  inner_instructions {
    index: 5
    instructions {
      program_id_index: 14
      accounts: "\004\006\003"
      data: "\003\377\200}4\376<\000\000"
      stack_height: 2
    }
    instructions {
      program_id_index: 9
      accounts: "\000\003"
      data: "\002\000\000\000\000\2245w\000\000\000\000"
      stack_height: 2
    }
    instructions {
      program_id_index: 9
      accounts: "\000\007"
      data: "\002\000\000\000\000-1\001\000\000\000\000"
      stack_height: 2
    }
    instructions {
      program_id_index: 10
      accounts: "\021"
      data: "\344E\245.Q\313\232\035\275\333\177\323N\346a\356\321\247\244\210\247\036\rs\004*\310e\303xf\017\027\335\371W5\032\233\326\221\365\2113\355\177\267Y\000\2245w\000\000\000\000\377\200}4\376<\000\000\001\240\266\257\003\351F\375 \254F\246\334\362\205\307\231"\010d;\037\325\277N\033{\3544\001l\346\024\214\034Mg\000\000\000\000\000@Ys\007\000\000\000\001\217Z\023\345\222\003\000\000\2245w\000\000\000\000\001\367G\307S\224\002\000"
      stack_height: 2
    }
  }
  log_messages: "Program ComputeBudget111111111111111111111111111111 invoke [1]"
  log_messages: "Program ComputeBudget111111111111111111111111111111 success"
  log_messages: "Program ComputeBudget111111111111111111111111111111 invoke [1]"
  log_messages: "Program ComputeBudget111111111111111111111111111111 success"
  log_messages: "Program 11111111111111111111111111111111 invoke [1]"
  log_messages: "Program 11111111111111111111111111111111 success"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P invoke [1]"
  log_messages: "Program log: Instruction: Create"
  log_messages: "Program 11111111111111111111111111111111 invoke [2]"
  log_messages: "Program 11111111111111111111111111111111 success"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]"
  log_messages: "Program log: Instruction: InitializeMint2"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2780 of 161315 compute units"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
  log_messages: "Program 11111111111111111111111111111111 invoke [2]"
  log_messages: "Program 11111111111111111111111111111111 success"
  log_messages: "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [2]"
  log_messages: "Program log: Create"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]"
  log_messages: "Program log: Instruction: GetAccountDataSize"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1595 of 140419 compute units"
  log_messages: "Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA="
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
  log_messages: "Program 11111111111111111111111111111111 invoke [3]"
  log_messages: "Program 11111111111111111111111111111111 success"
  log_messages: "Program log: Initialize the associated token account"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]"
  log_messages: "Program log: Instruction: InitializeImmutableOwner"
  log_messages: "Program log: Please upgrade to SPL Token 2022 for immutable owner support"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 133806 compute units"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]"
  log_messages: "Program log: Instruction: InitializeAccount3"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4214 of 129922 compute units"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
  log_messages: "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 20490 of 145894 compute units"
  log_messages: "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success"
  log_messages: "Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [2]"
  log_messages: "Program log: IX: Create Metadata Accounts v3"
  log_messages: "Program 11111111111111111111111111111111 invoke [3]"
  log_messages: "Program 11111111111111111111111111111111 success"
  log_messages: "Program log: Allocate space for the account"
  log_messages: "Program 11111111111111111111111111111111 invoke [3]"
  log_messages: "Program 11111111111111111111111111111111 success"
  log_messages: "Program log: Assign the account to the owning program"
  log_messages: "Program 11111111111111111111111111111111 invoke [3]"
  log_messages: "Program 11111111111111111111111111111111 success"
  log_messages: "Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 35130 of 111661 compute units"
  log_messages: "Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s success"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]"
  log_messages: "Program log: Instruction: MintTo"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4492 of 74016 compute units"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]"
  log_messages: "Program log: Instruction: SetAuthority"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2911 of 67377 compute units"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P invoke [2]"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P consumed 2003 of 60187 compute units"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P success"
  log_messages: "Program data: G3KpTd7rY3YTAAAAT2ZmaWNpYWwgU3RvcnkgQS5JIAcAAABTdG9yeUFJQwAAAGh0dHBzOi8vaXBmcy5pby9pcGZzL1FtUWo0RlRuWXNVYzVubVU1Z2RKa0R3b2RWdkJlUVFNVjVOTW5nOWE5YXBTZXPRp6SIpx4NcwQqyGXDeGYPF935VzUam9aR9Ykz7X+3WZrCATajhwmN+IHft/qMH0VF1VaTsVnrlBahofqQ0KLkoLavA+lG/SCsRqbc8oXHmSIIZDsf1b9OG3vsNAFs5hQ="
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P consumed 116567 of 172865 compute units"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P success"
  log_messages: "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]"
  log_messages: "Program log: CreateIdempotent"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]"
  log_messages: "Program log: Instruction: GetAccountDataSize"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1569 of 49397 compute units"
  log_messages: "Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA="
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
  log_messages: "Program 11111111111111111111111111111111 invoke [2]"
  log_messages: "Program 11111111111111111111111111111111 success"
  log_messages: "Program log: Initialize the associated token account"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]"
  log_messages: "Program log: Instruction: InitializeImmutableOwner"
  log_messages: "Program log: Please upgrade to SPL Token 2022 for immutable owner support"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 42810 compute units"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]"
  log_messages: "Program log: Instruction: InitializeAccount3"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4188 of 38930 compute units"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
  log_messages: "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 21839 of 56298 compute units"
  log_messages: "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P invoke [1]"
  log_messages: "Program log: Instruction: Buy"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]"
  log_messages: "Program log: Instruction: Transfer"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4645 of 15816 compute units"
  log_messages: "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
  log_messages: "Program 11111111111111111111111111111111 invoke [2]"
  log_messages: "Program 11111111111111111111111111111111 success"
  log_messages: "Program 11111111111111111111111111111111 invoke [2]"
  log_messages: "Program 11111111111111111111111111111111 success"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P invoke [2]"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P consumed 2003 of 3728 compute units"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P success"
  log_messages: "Program data: vdt/007mYe7Rp6SIpx4NcwQqyGXDeGYPF935VzUam9aR9Ykz7X+3WQCUNXcAAAAA/4B9NP48AAABoLavA+lG/SCsRqbc8oXHmSIIZDsf1b9OG3vsNAFs5hSMHE1nAAAAAABAWXMHAAAAAY9aE+WSAwAAlDV3AAAAAAH3R8dTlAIA"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P consumed 34459 of 34459 compute units"
  log_messages: "Program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P success"
  post_token_balances {
    account_index: 4
    mint: "F7QURpTCaFhHnLtCDVYqPQdAAbwhFVUG8AiNwytb4o7E"
    ui_token_amount {
      ui_amount: 932937500.000001
      decimals: 6
      amount: "932937500000001"
      ui_amount_string: "932937500.000001"
    }
    owner: "BR7N8Gnnoc2Jy3MMaUJfm5kZFZe7cUa5vLKbaHxN5NU3"
    program_id: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
  }
  post_token_balances {
    account_index: 6
    mint: "F7QURpTCaFhHnLtCDVYqPQdAAbwhFVUG8AiNwytb4o7E"
    ui_token_amount {
      ui_amount: 67062499.999999
      decimals: 6
      amount: "67062499999999"
      ui_amount_string: "67062499.999999"
    }
    owner: "BpMoHScowqzrY8vdi6MTcXckRahg9NCbqtD9K4YDcqP1"
    program_id: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
  }
  return_data_none: true
  compute_units_consumed: 173315
}
index: 377`

**Comment by benjiqq** [comment]
@PUXLBIY wdym exactly? what  grpc client is this
