### ISSUE TITLE
Inconsistent Blockhash between Solana and Yellowstone geyser plugin

### ISSUE THREAD

**Issue by vexelgray** [rpcpool/yellowstone-grpc#348]
Hello!

I have configured my dedicated RPC with Solv v. 4.1.4 and the yellowstone-grpc-geyser plugin version 1.14.2+solana.1.18.14. Everything seems to be going well; however, I have noticed that when I send a transaction, I always get the message that the blockhash has expired. Debugging, I observed that when I obtain the blockhash using the getLatestBlockhash function from the Yellowstone plugin, it seems to be always 300 blocks behind the getLatestBlockhash from Solana.

Here is a snippet of the code I am using:

```
const blockhash_solana = await this.connection.getLatestBlockhash(this.connection.commitment);
const blockhash_geyser = await this.geyserConnection.getLatestBlockhash(1);
logger.info(`Blochash solana: ${blockhash_solana.lastValidBlockHeight}`);
logger.info(`Blochash geyser: ${blockhash_geyser.lastValidBlockHeight}`);
```

```
[04:25:55.663] INFO: Blochash solana: 247732921
[04:25:55.663] INFO: Blochash geyser: 247732621

[07:01:59.520] INFO: Blochash solana: 247752272
[07:01:59.520] INFO: Blochash geyser: 247751972

[07:02:29.120] INFO: Blochash solana: 247752338
[07:02:29.120] INFO: Blochash geyser: 247752038
```

I always get that blockhash_geyser is 300 blocks behind.

Here is the version information for the geyser plugin I am using:

```
{
"version": {
  "package": "yellowstone-grpc-geyser",
  "version": "1.14.2+solana.1.18.14",
  "proto": "1.14.0+solana.1.18.14",
  "solana": "1.18.14",
  "git": "22d5c28",
  "rustc": "1.75.0",
  "buildts": "2024-05-21T20:03:23.392031044Z"
 }
}
```

Does anyone know what might be happening?

Thank you in advance for your help!

**Comment by fanatid** [comment]
Thanks for the report, should be fixed in #349
