### ISSUE TITLE
What is X token?

### ISSUE THREAD

**Issue by czaacza** [rpcpool/yellowstone-grpc#365]
Hi,
I want to connect with the self hosted Jupiter Swap Api, and there's the requirement for the yellowstone-x-token. What is it and where I can define it? I think it might be required to authenticate our request to the yellowstone client, but how to find or set the X-token?

**Comment by Juanito87** [comment]
x-token will depend on your rpc provider. You won't be able to run jupiter swsap api load on a public/freee endpoint.

**Comment by czaacza** [comment]
> x-token will depend on your rpc provider. You won't be able to run jupiter swsap api load on a public/freee endpoint.

Hi, thank you for your answer. 
I am running jupiter swap api for my own solana node. How to find the x-token for my own node? Do we set it in some config?

**Comment by Juanito87** [comment]
if you self host solana, you shouldn't use x-token, your locsl url dhould work. Jupiter swap may push your node behind.

**Comment by czaacza** [comment]
I've tried putting the Jupiter Swap Api on the Solana machine and indeed it was pushing the node behind. Therefore, I thought of putting it on an external machine, making requests to our Solana machine, to maybe avoid the block delays. Do you know if the x-token is useful in this case? So that we define it on the Solana machine to exterally connect with it from the swap api on another machine? Do you have any suggestions on how to properly host the Jupiter Swap Api avoiding the block delays? I've been struggling with this issue for a long time and we've been searching for the answer how to best host the API.

**Comment by Juanito87** [comment]
The node will be pushed behind, because of  the swap api workload. Getting a hosted service for the api is probably easier.
The x-token is irrelevant to the solana node performance. You should have a solana node that is not open to the world.

**Comment by Juanito87** [comment]
If you want to pass the x-token to your swap api, you'll need to setup your solana node for that. This is out of the scope of this repo. Running the api externally of the solana node won't garavtee you that the node will not be pushed behind.
