### ISSUE TITLE
update grpc-client and grpc-proto crates on crates.io

### ISSUE THREAD

**Issue by limonfort** [rpcpool/yellowstone-grpc#371]
https://crates.io/crates/yellowstone-grpc-proto
https://crates.io/crates/yellowstone-grpc-client

solana dependencies are a bit outdated

using this github repo is also hard if your current project not using workspaces, i tried changing cargo.toml files to be package instead of a workspace, and im getting several issues, might be my developer skills, but it would be great if you have some suggestions

**Comment by limonfort** [comment]
its my dumbass, sorry.

Use this snippet inside your cargo.toml if you want to use github repo:

`[dependencies]
yellowstone-grpc-geyser = { git = "https://github.com/rpcpool/yellowstone-grpc", package = "yellowstone-grpc-geyser" }
yellowstone-grpc-client = { git = "https://github.com/rpcpool/yellowstone-grpc", package = "yellowstone-grpc-client" }`

**Comment by fanatid** [comment]
to publish a new crate we need to bump proto crate version... we going to introduce some new filters and then make a release
