### ISSUE TITLE
error with ```segmentation fault (core dumped)```

### ISSUE THREAD

**Issue by Quan3Xin** [rpcpool/yellowstone-grpc#382]
`Initializing...                                                                                             [1]    1891786 segmentation fault (core dumped)  ./solana-test-validator -r --geyser-plugin-config ~/co.json`
* The solana version. 1.18.18
*  rustc version 1.75.0 
* linux ubuntu 22.0
configuration
`{
    "libpath": "/root/yellowstone-grpc/target/debug/libyellowstone_grpc_geyser.rlib",
    "log": {
        "level": "info",
	"file":"log.log"
    },
    "grpc": {
        "address": "0.0.0.0:10001",
        "compression": {
            "accept": [
                "gzip"
            ],
            "send": [
                "gzip"
            ]
        },
        "max_decoding_message_size": "4_194_304",
        "snapshot_plugin_channel_capacity": null,
        "snapshot_client_channel_capacity": "50_000_000",
        "channel_capacity": "100_000",
        "unary_concurrency_limit": 100,
        "unary_disabled": false,
        "x_token": null,
        "filters": {
            "accounts": {
                "max": 1,
                "any": false,
                "account_max": 10,
                "account_reject": [
                    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
                ],
                "owner_max": 10,
                "owner_reject": [
                    "11111111111111111111111111111111"
                ]
            },
            "slots": {
                "max": 1
            },
            "transactions": {
                "max": 1,
                "any": false,
                "account_include_max": 10,
                "account_include_reject": [
                    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
                ],
                "account_exclude_max": 10,
                "account_required_max": 10
            },
            "transactions_status": {
                "max": 1,
                "any": false,
                "account_include_max": 10,
                "account_include_reject": [
                    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
                ],
                "account_exclude_max": 10,
                "account_required_max": 10
            },
            "blocks": {
                "max": 1,
                "account_include_max": 10,
                "account_include_any": false,
                "account_include_reject": [
                    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
                ],
                "include_transactions": true,
                "include_accounts": false,
                "include_entries": false
            },
            "blocks_meta": {
                "max": 1
            },
            "entry": {
                "max": 1
            }
        }
    },
    "prometheus": {
        "address": "0.0.0.0:8999"
    },
    "block_fail_action": "log"
}
`

**Comment by Juanito87** [comment]
Does the plugin version and the solana version match?

**Comment by Quan3Xin** [comment]
> Does the plugin version and the solana version match?

Yes, With my solana version ( 1.18.18) I was using https://github.com/rpcpool/yellowstone-grpc/releases/download/v1.15.0%2Bsolana.1.18.18/yellowstone-grpc-geyser-release22-x86_64-unknown-linux-gnu.tar.bz2 this package.

**Comment by Quan3Xin** [comment]
> Does the plugin version and the solana version match?

So, That's problem mismatch version ?

**Comment by fanatid** [comment]
```
"libpath": "/root/yellowstone-grpc/target/debug/libyellowstone_grpc_geyser.rlib"
```
should be `so` file and never run debug version
you can use already compiled library instead of building it yourself https://github.com/rpcpool/yellowstone-grpc/releases/download/v1.15.0%2Bsolana.1.18.18/yellowstone-grpc-geyser-release22-x86_64-unknown-linux-gnu.tar.bz2

**Comment by Quan3Xin** [comment]
> ```
> "libpath": "/root/yellowstone-grpc/target/debug/libyellowstone_grpc_geyser.rlib"
> ```
> 
> should be `so` file and never run debug version you can use already compiled library instead of building it yourself https://github.com/rpcpool/yellowstone-grpc/releases/download/v1.15.0%2Bsolana.1.18.18/yellowstone-grpc-geyser-release22-x86_64-unknown-linux-gnu.tar.bz2

My wrong,  When i using that share library and fix config file to ```    "libpath": "/root/yellowstone-grpc-geyser-release/lib/libyellowstone_grpc_geyser.so",
``` . 
Also check Solana version with 1.18.18 and rustc is 1.175.0
<img width="522" alt="Snipaste_2024-07-24_23-55-00" src="https://github.com/user-attachments/assets/840a989a-4a92-469c-b8f9-13d5731ba7e2">

**Comment by Quan3Xin** [comment]
I fix that , is config file error , I add other params with config so  dumps. Thx
