### ISSUE TITLE
Error: 16 UNAUTHENTICATED: No valid auth token

### ISSUE THREAD

**Issue by daanrod** [rpcpool/yellowstone-grpc#388]
Jacopo from helius has updated this issue foir nodejs

I have updated the installed again with npm install or update and dont work for me.

**Comment by Lusitaniae** [comment]
can you provide full logs please including the commands your'e running

**Comment by fanatid** [comment]
#387 is not published on npm yet

**Comment by heymike-sol** [comment]
Is there any chance it will be published on NPM soon?

**Comment by fanatid** [comment]
@heymike-sol sorry for delay, published as v0.6.0 https://www.npmjs.com/package/@triton-one/yellowstone-grpc/v/0.6.0
