### ISSUE TITLE
Dependency Conflict: solana_rbpf = "=0.8.0" Not Found in crates.io for solana-program-runtime v1.18.20

### ISSUE THREAD

**Issue by youzi28** [rpcpool/yellowstone-grpc#394]
Hello,
I'm encountering an issue with a dependency conflict when building a project that relies on solana-program-runtime v1.18.20. The build process fails with the following error:

`error: failed to select a version for the requirement solana_rbpf = "=0.8.0"
candidate versions found which didn't match: 0.8.5, 0.8.4, 0.8.3, ...
location searched: crates.io index
required by package solana-program-runtime v1.18.20
    ... which satisfies dependency solana-program-runtime = "=1.18.20" of package solana-config-program v1.18.20
    ... which satisfies dependency solana-config-program = "=1.18.20" of package solana-account-decoder v1.18.20
    ... which satisfies dependency solana-account-decoder = "=1.18.20" of package solana-transaction-status v1.18.20
    ... which satisfies dependency solana-transaction-status = "=1.18.20" of package yellowstone-grpc-client-simple v1.13.0+solana.1.18.20 (/home/sol/yellowstone-grpc/examples/rust)
perhaps a crate was updated and forgotten to be re-vendored?
`

I attempted to update the solana_rbpf version to 0.8.5 in both Cargo.toml and Cargo.lock files, but the error persists

**Comment by SCcagg5** [comment]
Up same issue here solana github has been updated about 16 hours ago to rbpf= `0.8.3`

**Comment by fanatid** [comment]
please try v1.18.22 release https://github.com/rpcpool/yellowstone-grpc/releases/tag/v1.15.0%2Bsolana.1.18.22
