### ISSUE TITLE
The metric connections_total{job="grpc"} seems counting wrong connections

### ISSUE THREAD

**Issue by pffont** [rpcpool/yellowstone-grpc#398]
This metric seems to count outgoing connections to port 10000, but there are connections to port 10000 that aren't grpc connections. For example, the metabase server (ams160).

The dashboard shows 7 connections most part of the time, but the customer complained about it, they said the number should be 4. 

https://metrics.rpcpool.com/d/adrg0pwo93gn4d/metabase-grpc?orgId=1&refresh=30s&from=now-1h&to=now&viewPanel=22

![image](https://github.com/user-attachments/assets/43e52a15-e9ff-49e8-b85a-49e96a56ddd5)

This server is open connections to validators on port 10000 and the number of connections is always the same of the dashboard

![image](https://github.com/user-attachments/assets/936fed10-6488-4662-97f9-cacdb280b440)

So, as the grpc service runs on port 10000, this metric could be counting connections to this port, even when the connection is not grpc.

**Comment by fanatid** [comment]
@dancamarg0 can you please explore connections and subscriptions with `/debug_clients` endpoint?

**Comment by pffont** [comment]
I tested on dub16 and It's working correctly, probably it was some misreading on metrics and ports.
