### ISSUE TITLE
Filter blocks by accounts and Accounts filter for accounts on the gRPC2Kafka Side and Implement Retry on Failure

### ISSUE THREAD

**Issue by mohsen-vybenetwork** [rpcpool/yellowstone-grpc#416]
I'm encountering an issue with filtering transactions and accounts on the GRPC2Kafka side. Specifically, when trying to filter blocks by accounts using include or exclude settings, the filters don't seem to have any effect.

Is there a way to properly filter blocks by accounts and accounts by exclude/include accounts on the gRPC2Kafka side? Could you please provide a sample configuration for including and excluding accounts?

Additionally, is there a way to configure gRPC2Kafka to automatically retry on failure instead of crashing? This would help maintain service continuity during transient errors.

As an example:
For accounts:

>      {
>     "grpc2kafka": {
>         "endpoint": "http://x.y.z.w:10000",
>         "request": {
>           "accounts": {
>             "clients": {
>                "include_accounts": ["XXXXX"]
>                 }
>          }
>         },

        
     
  And for block like below it doesn't push any data:

>        "request": {
>           "blocks": {
>             "clients": {
>                     "account_include": [],
>                     "include_transactions": false,
>                     "include_accounts": true,
>                     "include_entries": false
>          }}
>         }

**Comment by fanatid** [comment]
please use transactions and accounts instead of blocks subscription, geyser does not provide a native interface for block notifications and we need to try to re-construct them every time, we can fail

> Additionally, is there a way to configure gRPC2Kafka to automatically retry on failure instead of crashing? This would help maintain service continuity during transient errors.

no, there is no such feature, you need to deploy at least 2 grpc2kafka instances with different sources and then deduplicate data before consumtion
