### ISSUE TITLE
Account filtering issue

### ISSUE THREAD

**Issue by mohsen-vybenetwork** [rpcpool/yellowstone-grpc#417]
Hey Team
Thank you for the great application!

I'm encountering an issue with the configuration for accounts, as shown below. The process fails after 30 seconds.

>   {
    "grpc2kafka": {
        "endpoint": "http://x.y.z.w:10000",
        "request": {
            "accounts": {
                "client": {
                    "include_accounts": ["Stake11111111111111111111111111111111111111"]
                }
            }
        },

The following error is returned:

>  Error: status: Internal, message: "lagged", details: [], metadata: MetadataMap { headers: {} }

**Comment by fanatid** [comment]
your connection doesn't consume messages fast enough, try to run grpc2kafka closer to the source (perfectly would be in the same DC)
