### ISSUE TITLE
Package TypeScript client as a library

### ISSUE THREAD

**Issue by nbaksalyar** [rpcpool/yellowstone-grpc#42]
- Separate the current example code from the library code.
- Provide a documented, user-friendly API.
- Provide TypeScript type definitions for RPC objects.
- Add more metadata for NPM.
- Add usage examples in readme.

**Comment by fanatid** [comment]
I think we can close it?

**Comment by fanatid** [comment]
Resolved with https://github.com/rpcpool/yellowstone-grpc/pull/142
