### ISSUE TITLE
Typescript client has TypeError: Client is not a constructor

### ISSUE THREAD

**Issue by samuel-kinetic** [rpcpool/yellowstone-grpc#428]
When I trying with the steps on https://docs.triton.one/project-yellowstone/dragons-mouth-grpc-subscriptions#nodejs-typescript, and save the following content in `get-version.ts`:

```
import Client from "@triton-one/yellowstone-grpc";

const main = async () => {
    const client = new Client(
        "http://some-grpc.host.com",
        "some-key", {
            "grpc.max_receive_message_length": 64 * 1024 * 1024 // 64 MB
        });
    
    // now you can call the client methods, e.g.:
    
    const version = await client.getVersion(); // gets the version information
    console.log(version);
}

main();
```

And I got the following error when running `npx esrun get-version.ts`:

```
  const client = new Client(
                 ^

TypeError: Client is not a constructor
```

Am I missing anything from the doc and how could we solve?

**Comment by Pleidak** [comment]
I am also having the same problem, I asked solana.stackexchange but no help either. Did you get a fix?

**Comment by samuel-kinetic** [comment]
Not fixed yet, still have the problem from my side.

**Comment by XingqiWang** [comment]
```
import Client from "@triton-one/yellowstone-grpc";

const main = async () => {
    const client = new Client.default(
        "http://some-grpc.host.com",
        "some-key", {
            "grpc.max_receive_message_length": 64 * 1024 * 1024 // 64 MB
        });
    
    // now you can call the client methods, e.g.:
    
    const version = await client.getVersion(); // gets the version information
    console.log(version);
}

main();
```

`new Client` to  `new Client.default`, it works for me

**Comment by XingqiWang** [comment]
```
import Client, {
    CommitmentLevel,
    SubscribeRequest,
    SubscribeRequestFilterAccountsFilter,
} from '@triton-one/yellowstone-grpc';

async function main() {

    const client = new Client.default('http://127.0.0.1:10001', undefined, {
        "grpc.max_receive_message_length": 64 * 1024 * 1024, // 64MiB
    });

    console.log("PROCESSED slot: " + (await client.getSlot(CommitmentLevel.PROCESSED)));
    console.log("FINALIZED slot: " + (await client.getSlot(CommitmentLevel.FINALIZED)));

    // Subscribe for events
    const stream = await client.subscribe();
    // Handle updates
    stream.on("data", (data) => {
        console.log("data", data);
    });

    // Create subscribe request based on provided arguments.
    const request = {
        accounts: {},
        slots: {
            client:{
                filterByCommitment: CommitmentLevel.CONFIRMED,
            }
        },
        transactions: {},
        transactionsStatus: {},
        entry: {},
        blocks: {},
        blocksMeta: {},
        accountsDataSlice: [],
        ping: undefined,
    };

    // Send subscribe request
    await new Promise<void>((resolve, reject) => {
        stream.write(request, (err) => {
            if (err === null || err === undefined) {
                resolve();
            } else {
                reject(err);
            }
        });
    }).catch((reason) => {
        console.error(reason);
        throw reason;
    });
}

main();
```

`new Client` to `new Client.default`, it works for me.

**Comment by atmikev** [comment]
I'm having the same issue. Using `Client.default`breaks type-hinting in Webstorm. Would love to see this fixed.

**Comment by yogioioi414** [comment]
> `new Client` to `new Client.default`, it works for me.
> 
> ```
> import Client, {
>     CommitmentLevel,
>     SubscribeRequest,
>     SubscribeRequestFilterAccountsFilter,
> } from '@triton-one/yellowstone-grpc';
> 
> async function main() {
> 
>     const client = new Client.default('http://127.0.0.1:10001', undefined, {
>         "grpc.max_receive_message_length": 64 * 1024 * 1024, // 64MiB
>     });
> 
>     console.log("PROCESSED slot: " + (await client.getSlot(CommitmentLevel.PROCESSED)));
>     console.log("FINALIZED slot: " + (await client.getSlot(CommitmentLevel.FINALIZED)));
> 
>     // Subscribe for events
>     const stream = await client.subscribe();
>     // Handle updates
>     stream.on("data", (data) => {
>         console.log("data", data);
>     });
> 
>     // Create subscribe request based on provided arguments.
>     const request = {
>         accounts: {},
>         slots: {
>             filterByCommitment: CommitmentLevel.CONFIRMED,
>         },
>         transactions: {},
>         transactionsStatus: {},
>         entry: {},
>         blocks: {},
>         blocksMeta: {},
>         accountsDataSlice: [],
>         ping: undefined,
>     };
> 
>     // Send subscribe request
>     await new Promise<void>((resolve, reject) => {
>         stream.write(request, (err) => {
>             if (err === null || err === undefined) {
>                 resolve();
>             } else {
>                 reject(err);
>             }
>         });
>     }).catch((reason) => {
>         console.error(reason);
>         throw reason;
>     });
> }
> 
> main();
> ```

thanks mate, this works

**Comment by 0xpolarzero** [comment]
Why was this closed as completed @fanatid? This breaks TypeScript.

**Comment by fanatid** [comment]
proposed solution: https://github.com/rpcpool/yellowstone-grpc/issues/428#issuecomment-2395513185
confirmation: https://github.com/rpcpool/yellowstone-grpc/issues/428#issuecomment-2452879995

it doesn't work for you?

**Comment by 0xFilosoF** [comment]
> proposed solution: [#428 (comment)](https://github.com/rpcpool/yellowstone-grpc/issues/428#issuecomment-2395513185) confirmation: [#428 (comment)](https://github.com/rpcpool/yellowstone-grpc/issues/428#issuecomment-2452879995)
> 
> it doesn't work for you?

I encountered the same issue. Most likely, there is no support for `ESM module`.
However, everything worked correctly when using [Bun.js](https://bun.sh/), but it does not work with Node.js v20.12.2.

My solution:
 - Removed `"type": "module"` from `package.json`
 - Updated parameters in `tsconfig.json`
```
    "lib": ["es2023"],
    "types": ["node"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
```
to
```
    "lib": ["es2023"],
    "types": ["node"],
    "target": "ES2022",
    "module": "CommonJS",
    "moduleResolution": "Node16",
