### ISSUE TITLE
empty xtoken

### ISSUE THREAD

**Issue by benjiqq** [rpcpool/yellowstone-grpc#454]
some provider use empty xtoken, rust client will fail here. I guess the provider is using xtoken incorreclty and its required

https://github.com/rpcpool/yellowstone-grpc/blob/master/yellowstone-grpc-client/src/lib.rs#L296

**Comment by fanatid** [comment]
hm, why they are using an empty x-token? but yeah, probably we need to remove this error and allow any value as x-token
would you like to create a PR? :slightly_smiling_face:

**Comment by benjiqq** [comment]
thanks. i have another provide who doesn't have this issue
