### ISSUE TITLE
Update Solana crates to 2.1

### ISSUE THREAD

**Issue by NicolasWent** [rpcpool/yellowstone-grpc#464]
Hello,

`yellowstone-grpc-client` and `yellowstone-grpc-proto` are not working with `solana-client`, `solana-sdk`... at version 2.1

Which ultimately leads to `spl-token` version 7.0 being incompatible with yellowstone-grpc

**Comment by fanatid** [comment]
Hi! This is in the plans, but first requires to finish work on https://github.com/rpcpool/yellowstone-grpc/pull/449
