### ISSUE TITLE
Segmenation Fault with v3 versions of Yellowstone 

### ISSUE THREAD

**Issue by NotArchon** [rpcpool/yellowstone-grpc#472]
Hi,

Whenever I run v3 versions of Yellowstone grpc with Agave, I get a segmenation fault error as grpc begins.

There's not much information other than "Segmentation fault"

I've ran Agave 2.0.16 with Yellowstone v2 2.0.16 and it works fine.
Even Agave 2.0.18 with Yellowstone v2 2.0.16 works.

However, anytime i use your v3 releases, segfault.

**Comment by Juanito87** [comment]
You should run agave and yellowstone compiled with the same rust version, and on matching solana versions.
For v3 it should be rust 1.78.

**Comment by Juanito87** [comment]
Solana version and plugin version should be compile with the same rust version. 
And solana version should match the plugin version, so agave 2.0.18 and plugin v3.0,0+solana.2..0.18.
Also even tho v2 may work, it's not a guarantee that it'll work on v3 because it's not the recommended way to do it.
