### ISSUE TITLE
Subscription latency 300 ms

### ISSUE THREAD

**Issue by RaydiumGOD** [rpcpool/yellowstone-grpc#476]
Hi,
I am running geyser on 2 nodes, VA and NY. Both resulting the same **300ms delay** for **transaction sub with processed** commitment, tested it **locally on the node** itself. On VPS delay reaches 1 second.  Code language used to test: **Rust**.

Comparison was made according to solscan timing of txn. 

Monitored the RPC regularly, didnt see ram exceeding 500-600GB. [atop,htop]

What could I be missing here?

**my config:**
```
{
    "libpath": "/home/sol/yellowstone-grpc/target/release/libyellowstone_grpc_geyser.so",
    "log": {
        "level": "debug"
    },
    "grpc": {
        "address": "0.0.0.0:10000",
        "max_decoding_message_size": "4_194_304",
        "channel_capacity": "100_000",
        "unary_concurrency_limit": 100,
        "unary_disabled": false
    },
    "block_fail_action": "log"
}
```

**RPC Specs [latitude]:**
CPU: AMD 9354P, 32 Cores @ 3.25 GHz
RAM: 768 GB RAM
STR: 2 x 480GB NVME + 2 x 8TB NVME
NIC: 2 x 100Gbps

Solana and Geyser version = 2.0.18

**Comment by Lusitaniae** [comment]
Would depend on your subscription params too

500-600GB this is already high

if you're running RPC + indexes, you'd need about 400gb available RAM for accounts in disk to be in Page Cache (RAM cache managed by Linus)
