### ISSUE TITLE
Source build fails: yellowstone-grpc-geyser v3.1.0 plugin interface dependency mismatch

### ISSUE THREAD

**Issue by heisenberg1995-ops** [rpcpool/yellowstone-grpc#490]
Building yellowstone-grpc-geyser v3.1.0 from source fails due to incompatible agave-geyser-plugin-interface dependencies, while the published binary release works correctly. The source build attempts to use a different version of the interface than what's included in the binary release.

Environment:
- agave v2.0.18 source
- yellowstone-grpc v3.1.0 source
- Both installed from source repositories

Could you check the geyser plugin interface dependency configuration for the source build? The binary release seems to have the correct dependency bundled but this is not reflected in the source build setup.

**Comment by fanatid** [comment]
Binary releases are created in CI from the tag, you can find the tag in the repo, and as you see dependencies are correct because the build was successful. If you can some errors on building, please paste error here, maybe then it would be possible to figure our your issue.

**Comment by heisenberg1995-ops** [comment]
When building without local dependencies, everything works fine. However, once I add the local `agave-geyser-plugin-interface` using:
```
agave-geyser-plugin-interface = { path = "../agave/agave-2.0.18/geyser-plugin-interface" }
```
I get 28 build errors. The core issue appears to be trait implementation mismatches between `spl_token_2022` dependencies, specifically around the Pack trait. For example:
```
error[E0277]: the trait bound spl_token_2022::state::Account: solana_sdk::program_pack::Pack is not satisfied
```
This suggests an incompatibility between the local agave interface and the expected dependencies in yellowstone. The binary release likely uses a different dependency resolution that avoids these conflicts.
