### ISSUE TITLE
gRPC fails to start with default replay_stored_slots value

### ISSUE THREAD

**Issue by heisenberg1995-ops** [rpcpool/yellowstone-grpc#495]
Version: yellowstone-geyser `v3.2.0`, agave `2.0.18`

The default config sets `"replay_stored_slots": 0` (boolean, false), but gRPC won't start with this value. Setting it to `1` (true) works but causes noticeable performance slowdown. How can I start the gRPC with the value `0`?

Reference: https://github.com/rpcpool/yellowstone-grpc/blob/master/yellowstone-grpc-geyser/config.json#L32

**Comment by fanatid** [comment]
Thank you!
New tags: https://github.com/rpcpool/yellowstone-grpc/releases/tag/v3.2.1%2Bsolana.2.0.18 + https://github.com/rpcpool/yellowstone-grpc/releases/tag/v4.2.1%2Bsolana.2.1.5

**Comment by heisenberg1995-ops** [comment]
Thank you for resolving the issue so quickly!
