### ISSUE TITLE
No connection established: routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by JIscariot** [rpcpool/yellowstone-grpc#501]
![Снимок экрана от 2024-12-19 13-49-52](https://github.com/user-attachments/assets/097bb17d-d237-4194-a91d-944fe65f3751)

**Comment by JIscariot** [comment]
https://github.com/rpcpool/yellowstone-grpc/pull/502

**Comment by fanatid** [comment]
Thank you! Closed in #502
