### ISSUE TITLE
No Updates on Slow-Moving Accounts

### ISSUE THREAD

**Issue by brianlong** [rpcpool/yellowstone-grpc#80]
From a client:

Heads up, the devnet geyser service seems to systematically go stale after a running for a while (quite a while)

I can see the periodic pings until I don't see them anymore, and subsequent updates are not picked up

unsure what it can be cause the stream remains intact so the client does not recover

I have not observed this on the mainnet client so not dire so far

**Comment by linuskendall** [comment]
Looks like this might be the same as #25

**Comment by fanatid** [comment]
do we still get such reports from the clients?

**Comment by fanatid** [comment]
I think we can move this issue to #175
